import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import titleImg from "public/title.png";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Quiz Solstice</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col items-center justify-center gap-10">
        <h1 className="text-5xl">Quiz Solstice</h1>
        <div className="flex flex-col items-center justify-center">
          <h2>Thank you to our sponsors</h2>
          <Image src={titleImg} height={100} width={300} alt="title" />
        </div>

        <Link className="underline" href="/play">
          Mulai
        </Link>
      </div>
    </>
  );
};

export default Home;
